### ISSUE TITLE
Host on firebase hosting instead of own server?

### ISSUE THREAD

**Issue by christiangrieger** [griffinsockwell/react-firebase-custom-email-handlers#2]
Hey,

is it possible to host this also on firebase hosting without react? I really would love to have my own email handlers but it would be nice to be able to store it on the firebase hosting instead of a seperated server. 

I also have a special question you maybe could help me on :) would be cool to get you on skype for some minutes: tiCeR89 

Greetings,
Chris

**Comment by griffinsockwell** [comment]
Hey Chris,

The app was created with [create-react-app](https://github.com/facebookincubator/create-react-app) so you should be able to deploy to firebase hosting with their [guide](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#firebase).

I would take a look through their deployment guide first and then if you have more questions just let me know.

Also I've been working on an update for this example app and I just haven't pushed it to GitHub yet. Hopefully by tonight I will have it completed.

**Comment by christiangrieger** [comment]
Hey Griffin,

sounds good :), would it be possible that you contact me on Skype?

Greetings,
Chris

**Comment by griffinsockwell** [comment]
It would probably be easier on me if you have any questions to send me an email at gs71312@icloud.com or gsockwell@gmail.com

**Comment by christiangrieger** [comment]
Okay i will try it :) Mail is sent.

**Comment by christiangrieger** [comment]
Worked perfect and its deployed on firebase hosting!!!! Thank you very much. Cant wait for the update.
