### ISSUE TITLE
Enable https for react?

### ISSUE THREAD

**Issue by christiangrieger** [griffinsockwell/react-firebase-custom-email-handlers#3]
Hey,

how would it be possible to enable https for the react app?

Greetings,
Chris

**Comment by griffinsockwell** [comment]
Firebase hosting uses https by default whether you are using the domain they give you or a custom domain. You can find more information about custom domains on firebase [here](https://firebase.google.com/docs/hosting/custom-domain).

**Comment by christiangrieger** [comment]
Okay so only the other issue stays open :)

**Comment by griffinsockwell** [comment]
With firebase hosting you don't need to start npm.

You run a build of your react app using a bundler like webpack.

For example if you are using create-react-app, you run npm build and then you deploy the build, which is static.

**Comment by christiangrieger** [comment]
So i will have to read this up again to understand.

**Comment by griffinsockwell** [comment]
Yeah my recommendation would be to create a new firebase project and then try and upload the default create-react-app to firebase hosting.

When you create a new react app with create-react-app you get some default scripts in your package.json:
```js
"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
```

`npm start` is used to start the development server only

`npm run build` will create a static build of the app

You will then upload the build folder to firebase hosting

I think if you go through the steps with the default app on a test firebase app it will be a bit more clear. The full steps can be found [here](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#firebase).

**Comment by christiangrieger** [comment]
Thank you very much! I will give it a try now. Did you get my email?

**Comment by griffinsockwell** [comment]
Yes I got your email and I wrote a response. Let me know if you got it.

**Comment by christiangrieger** [comment]
Hey, no i did not get the mail :/, added you to the whitelist.

**Comment by griffinsockwell** [comment]
Alright I sent the response again.
